apiVersion: v1
kind: Service
metadata:
  name: otel-node
spec:
  selector:
    app: otel-node
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-node
  labels:
    app: otel-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-node
  template:
    metadata:
      labels:
        app: otel-node
    spec:
      containers:
        - name: otel-node
          image: tobsirl/otel-node:latest
          ports:
            - containerPort: 8080
